name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  # Regularily run the test since Pluto internals can change at any moment.
  schedule:
    - cron: '00 04 * * 3,6'

jobs:
  Test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1.7'
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v1
        with:
          cache-registries: "true"
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_NUM_THREADS: 2
